### ISSUE TITLE
ValueError: for atom type POT, 0 parameters found (expecting 1, found: [])

### ISSUE THREAD

**Issue by odraccix** [resal81/PyTopol#28]
Hi resal81 and everyone,
I had a similar problem to that of krlitros87 (https://github.com/resal81/PyTopol/issues/23).
I have a system composed by a membrane protein in which several ions ( K+, Na+, Cl-) are present both in the selective filter (K+) of the channel protein and in the solvation box (K+, Na+, Cl-).

I'm using par_all36_lipid.prm, par_all36_prot.prm, toppar/toppar_water_ions.str as the parameters file, but it seems that this choice was not good, although it tried to replace K atom type with POT and vice versa.
## This is my output..

mainapp                        - DEBUG    - >> started main
mainapp.psf.PSFSystem          - DEBUG    - >> entering PSFSystem
mainapp.psf.PSFSystem          - DEBUG    - parsing psf file: sodium.psf
mainapp.psf.PSFSystem          - WARNING  - could not find NAMD keywork in the first line in the psf file
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '33 !NTITLE'
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '0 !NDON: donors'
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '0 !NACC: acceptors'
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '0 !NNB'
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '1       0 !NGRP'
mainapp.psf.PSFSystem          - DEBUG    - parsing took  7.7 seconds
mainapp.psf.PSFSystem          - DEBUG    - << leaving PSFSystem
mainapp.psf.PSFSystem          - DEBUG    - converting psf to multiple molecules based on chains
mainapp.charmmpar.CharmmPar    - DEBUG    - >> entering CharmmPar
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing parameter file: par_all36_prot.prm
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing took  0.0 seconds
mainapp.charmmpar.CharmmPar    - DEBUG    - 132 bonding, 362 angle, 546 dih,  35 imp,  53 nonbonding and  6 cmaps
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing parameter file: par_all36_lipid.prm
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing took  0.0 seconds
mainapp.charmmpar.CharmmPar    - DEBUG    - 182 bonding, 493 angle, 650 dih,  39 imp,  82 nonbonding and  6 cmaps
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing parameter file: toppar_water_ions_Matteo_edit.str
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing took  0.0 seconds
mainapp.charmmpar.CharmmPar    - DEBUG    - 182 bonding, 493 angle, 650 dih,  39 imp,  82 nonbonding and  6 cmaps
mainapp.charmmpar.CharmmPar    - DEBUG    - << leaving CharmmPar
mainapp.charmmpar.CharmmPar    - DEBUG    - adding parameters to the system...
**Traceback (most recent call last):
  File "psf2top.py", line 107, in <module>
    main()
  File "psf2top.py", line 96, in main
    par.add_params_to_system(psfsys, panic_on_missing_param=True)
  File "/usr/local/lib/python2.7/dist-packages/pytopol/parsers/charmmpar.py", line 296, in add_params_to_system
    raise ValueError(msg)
ValueError: for atom type POT, 0 parameters found (expecting 1, found: [])**

---

Hoping it will be useful to solve the problem... because this issue makes me crazy!!

Thank you in advance

**Comment by resal81** [comment]
Hi odraccix, 

It looks like that your last param file is not parsed correctly:

```
mainapp.charmmpar.CharmmPar - DEBUG - parsing parameter file: par_all36_prot.prm
mainapp.charmmpar.CharmmPar - DEBUG - parsing took 0.0 seconds
mainapp.charmmpar.CharmmPar - DEBUG - 132 bonding, 362 angle, 546 dih, 35 imp, 53 nonbonding and 6 cmaps
mainapp.charmmpar.CharmmPar - DEBUG - parsing parameter file: par_all36_lipid.prm
mainapp.charmmpar.CharmmPar - DEBUG - parsing took 0.0 seconds
mainapp.charmmpar.CharmmPar - DEBUG - 182 bonding, 493 angle, 650 dih, 39 imp, 82 nonbonding and 6 cmaps
mainapp.charmmpar.CharmmPar - DEBUG - parsing parameter file: toppar_water_ions_Matteo_edit.str
mainapp.charmmpar.CharmmPar - DEBUG - parsing took 0.0 seconds
mainapp.charmmpar.CharmmPar - DEBUG - 182 bonding, 493 angle, 650 dih, 39 imp, 82 nonbonding and 6 cmaps
```

Note how the number of parameters (i.e. nonbonding, ...) is not changed after reading `toppar_water_ions_Matteo_edit.str`. One thing you can do is to extract the parameter section of the `str` file into another file (basically anything between `read_para` and the final `END`) and try it out. Hopefully this will solve the problem.
