### ISSUE TITLE
ValueError: for atom type OT, 0 parameters found (expecting 1, found: [])

### ISSUE THREAD

**Issue by anitaknivedha** [resal81/PyTopol#29]
I am running psf2top.py using Python 2.7.13 and I am running into this error.

Command: **python psf2top.py -p system.psf -c toppar/par_all36m_prot.prm toppar/liga_hyd.par  toppar/par_water_ions.par -v**
Verbose Output: 
```
    ------------------------------------------------------------------------
    PyTopol version 0.1.7 (latest available online version: 0.1.7).

    ------------------------------------------------------------------------
    Please note that this version is considered alpha and the generated
    topologies should be validated before being used in production
    simulations.

    For more info, please see: http://github.com/resal81/pytopol
    ------------------------------------------------------------------------
    
mainapp                        - DEBUG    - >> started main
mainapp.psf.PSFSystem          - DEBUG    - >> entering PSFSystem
mainapp.psf.PSFSystem          - DEBUG    - parsing psf file: system.psf
mainapp.psf.PSFSystem          - WARNING  - could not find NAMD keywork in the first line in the psf file
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '3 !NTITLE'
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '592 !NDON: donors'
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '509 !NACC: acceptors'
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '0 !NNB'
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '1591       0 !NGRP NST2'
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '1 !MOLNT'
mainapp.psf.PSFSystem          - DEBUG    - skipping section: '0       0 !NUMLP NUMLPH'
mainapp.psf.PSFSystem          - DEBUG    - parsing took  0.6 seconds
mainapp.psf.PSFSystem          - DEBUG    - << leaving PSFSystem
mainapp.psf.PSFSystem          - DEBUG    - converting psf to multiple molecules based on chains
mainapp.charmmpar.CharmmPar    - DEBUG    - >> entering CharmmPar
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing parameter file: toppar/par_all36m_prot.prm
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing took  0.0 seconds
mainapp.charmmpar.CharmmPar    - DEBUG    - 132 bonding, 364 angle, 550 dih,  35 imp,  53 nonbonding and  6 cmaps
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing parameter file: toppar/liga_hyd.par
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing took  0.0 seconds
mainapp.charmmpar.CharmmPar    - DEBUG    - 142 bonding, 386 angle, 587 dih,  56 imp,  60 nonbonding and  6 cmaps
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing parameter file: toppar/par_water_ions.par
mainapp.charmmpar.CharmmPar    - DEBUG    - parsing took  0.0 seconds
mainapp.charmmpar.CharmmPar    - DEBUG    - 142 bonding, 386 angle, 587 dih,  56 imp,  60 nonbonding and  6 cmaps
mainapp.charmmpar.CharmmPar    - DEBUG    - << leaving CharmmPar
mainapp.charmmpar.CharmmPar    - DEBUG    - adding parameters to the system...
adding pair param to the mol for CAL-OC2D2
adding pair param to the mol for CAL-OCL
adding pair param to the mol for SOD-OCL
adding pair param to the mol for SOD-OC2D1
adding pair param to the mol for CAL-OC2DP
adding pair param to the mol for SOD-OC2DP
adding pair param to the mol for SOD-OC
adding pair param to the mol for CAL-CLA
adding pair param to the mol for SOD-O2L
adding pair param to the mol for NC2-OC
adding pair param to the mol for SOD-OC2D2
adding pair param to the mol for CAL-O2L
adding pair param to the mol for SOD-OG2D2
adding pair param to the mol for SOD-OBL
adding pair param to the mol for SOD-OG2P1
Traceback (most recent call last):
  File "/projects/Common/PYTHON/Python-2.7.13/bin/psf2top.py", line 107, in <module>
    main()
  File "/projects/Common/PYTHON/Python-2.7.13/bin/psf2top.py", line 96, in main
    par.add_params_to_system(psfsys, panic_on_missing_param=True)
  File "/projects/Common/PYTHON/Python-2.7.13/lib/python2.7/site-packages/pytopol/parsers/charmmpar.py", line 296, in add_params_to_system
    raise ValueError(msg)
ValueError: for atom type OT, 0 parameters found (expecting 1, found: [])
Traceback (most recent call last):
  File "/projects/Common/PYTHON/Python-2.7.13/bin/psf2top.py", line 107, in <module>
    main()
  File "/projects/Common/PYTHON/Python-2.7.13/bin/psf2top.py", line 96, in main
    par.add_params_to_system(psfsys, panic_on_missing_param=True)
  File "/projects/Common/PYTHON/Python-2.7.13/lib/python2.7/site-packages/pytopol/parsers/charmmpar.py", line 296, in add_params_to_system
    raise ValueError(msg)
ValueError: for atom type OT, 0 parameters found (expecting 1, found: [])
```

Do you have an idea why this might be happening? My water and ions parameter file does contain the atomtype OT:
```
ATOMS
MASS  -1  HT         1.00800 ! TIPS3P WATER HYDROGEN
MASS  -1  HX         1.00800 ! hydroxide hydrogen
MASS  -1  OT        15.99940 ! TIPS3P WATER OXYGEN     ! here
MASS  -1  OX        15.99940 ! hydroxide oxygen
MASS  -1  LIT        6.94100 ! Lithium ion
MASS  -1  SOD       22.98977 ! Sodium Ion
MASS  -1  MG        24.30500 ! Magnesium Ion
MASS  -1  POT       39.09830 ! Potassium Ion
MASS  -1  CAL       40.08000 ! Calcium Ion
MASS  -1  RUB       85.46780 ! Rubidium Ion
MASS  -1  CES      132.90545 ! Cesium Ion
MASS  -1  BAR      137.32700 ! Barium Ion
MASS  -1  ZN        65.37000 ! zinc (II) cation
MASS  -1  CAD      112.41100 ! cadmium (II) cation
MASS  -1  CLA       35.45000 ! Chloride Ion
```

Any insight into this is appreciated. I have already gone through both of the earlier posts with similar issues: [issue 28 ](https://github.com/resal81/PyTopol/issues/28) and [issue 23](https://github.com/resal81/PyTopol/issues/23), but those don't help to fix mine.

**Comment by anitaknivedha** [comment]
I fixed this issue by downloading the par_wations.par file from this git repo.
